project/forms.py
from flask_wtf import FlaskForm 
from flask_wtf.file import FileAllowed, FileField
from wtforms import ValidationError
from project.model import Users
from project import db 
from wtforms import StringField,SubmitField,PasswordField,IntegerField
from werkzeug.security import generate_password_hash,check_password_hash
from wtforms.validators import Email,EqualTo,DataRequired

### USER AREA
class RegisterForm(FlaskForm):
    userId = IntegerField('User Id',validators=[DataRequired()])
    name = StringField('Name',validators=[DataRequired()])
    password = PasswordField('Password',validators=[DataRequired()])
    password2 = PasswordField(
        'Confirm password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register!')
    def validate_userId(self, userId):
        if Users.query.filter_by(userId = userId.data).first():
            raise ValidationError('user another user Id')
    
class RoomBookForm(FlaskForm):
    checkIn = StringField('Check-In Date',validators=[DataRequired()],render_kw={"placeholder":"dd/mm/yyyy"})
    checkOut = StringField('Check-Out Date',validators=[DataRequired()],render_kw={"placeholder":"dd/mm/yyyy"})
    totalMembers = IntegerField('Total Visiting Member',validators = [DataRequired()],render_kw={"placeholder":"Total Visiting Members"})
    submit = SubmitField('Proceed to pay')
   
class checkOutForm(FlaskForm):
    userId = IntegerField('UserId',validators = [DataRequired()],render_kw={"placeholder":"Enter Unique User ID"})
        hotelId = StringField('Hotel ID',validators=[DataRequired()],render_kw={"placeholder":"Enter Hotel ID"})
        roomNo = StringField('Room Number',validators=[DataRequired()],render_kw={"placeholder":"Enter Room Number"})
        submit = SubmitField('Check-Out User') 
    
class UserLoginForm(FlaskForm):
    userId = StringField('UserId', validators=[DataRequired()], render_kw={"placeholder":"User Id"})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={"placeholder":"Password"})
    submit = SubmitField('Login')
### ENDS USER AREA

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
from flask_migrate import Migrate
from flask_login import LoginManager

app= Flask(__name__)
app.config['SECRET_KEY'] = 'mykey'

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

login_manager = LoginManager()

app.static_folder = 'static'

login_manager.init_app(app)
# login_manager.login_view = 'admin.book_room'

from project.routes import admin

app.register_blueprint(admin)

project/routes.py
from flask import *
from project import db
from project.model import Users,Handler, Rooms, Room_allotted, Drafts,Hotels,Facilities
from project.forms import UserLoginForm, RegisterForm, RoomBookForm, checkOutForm
from flask_login import login_user, current_user, logout_user, login_required
from project.picture_handler import add_profile_pic
import stripe
import os
from project.script import name,address 
from sqlalchemy import and_
from datetime import datetime
from werkzeug.urls import url_parse
# print(hotel_info)

admin = Blueprint('admin',__name__)

stripe_keys = {
  'publishable_key': "pk_test_EzB9rTKHvSb9uZwjzbv8q6kz00tdsUMFq0",
  'secret_key': "sk_test_SHwhbYRWt8S9ff2PfHhLthwq00M7u3Yppv"
}

stripe.api_key = stripe_keys['secret_key']

@admin.route('/')
def index():
    # db.drop_all()
    # db.create_all()
    return render_template('index.html')

# users area #####################################################################

@admin.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('admin.index'))

def facilities_function():
    x = Facilities.query.all()
    L = []
    for x in x :
        facilities = {}
        if x.gym is True:
            facilities['gym'] = True
        if x.FoodBeverages is True:
            facilities['FoodBeverages'] = True
        if x.Parking is True:
            facilities['Parking'] = True  
        if x.Tv is True:
            facilities['Tv'] = True
        if x.wifi is True:
            facilities['wifi'] = True 
        L.append(facilities)  
    return L

 
@admin.route('/signup', methods=['GET', 'POST'])
def signup():
    # if current_user.is_authenticated:
        # return redirect(url_for('admin.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        user = Users(userId=form.userId.data, name=form.name.data,password = form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('admin.index'))
    return render_template('signup.html', title='Register', form=form)
 

@admin.route('/userlogin', methods=['GET', 'POST'])
def UserLogin():
    # if current_user.is_authenticated:
        # return redirect(url_for('admin.index'))
    form = UserLoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(userId = form.userId.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid Credentials')
            return render_template('userlogin.html',form=form)
        # flash('Logged in successfully.')
        login_user(user)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('admin.index')
        return redirect(next_page)
         # return render_template(url_for('admin.UserLogin'))
    return render_template('userlogin.html', form=form)


 
data = {}
  
@admin.route('/userDashboard', methods=['GET', 'POST'])
def userDashboard():
    # Rooms.query.filter_by(roomNo = roomNo, hotelId = hotelId).first().status = False
    # Room_allotted.query.filter_by(roomNo = roomNo, hotelId = hotelId).first().paymentStatus = False    
    # db.session.commit()
    x = Users.query.filter_by(userId = current_user.userId).first()
    if x is not None:
        print(x.name)
    y = drafts = Drafts.query.filter_by(userId = current_user.userId).first()
    if y is not None:
        print(y.hotelId)
    # for each in drafts:
    #     for x in each:
    #         print(x.userId,x.hotelId,x.roomNo)

    return render_template('userDashboard.html')
 

@admin.route('/adminlogin', methods=['GET', 'POST'])
def adminLogin():
    # if current_user.is_authenticated:
        # return redirect(url_for('admin.index'))
    form = UserLoginForm()
    print('ok')
    if form.validate_on_submit():
        administrator = Handler.query.filter_by(adminId = form.userId.data).first()
        if administrator is not None and  administrator.check_password(form.password.data):
            login_user(administrator)
            return render_template('adminDashboard.html',form=form)
            
        flash('Invalid Credentials')
        # next_page = request.args.get('next')
        # if not next_page or url_parse(next_page).netloc != '':
            # next_page = url_for('admin.index')
        # return redirect(next_page)
        # return render_template(url_for('admin.UserLogin'))
    return render_template('adminLogin.html',form=form)

@admin.route('/adminDashboard', methods=['GET', 'POST'])
def adminDashboard():
    return render_template('adminDashboard.html')
   

################# Recommendation Funciton Implemented Here ################
from recommendation import similarity_hotel
def recommendation_function():
    alloted = Room_allotted.query.filter_by(userId = current_user.userId)
    booked_hotel = []
    if alloted is not None:
        for each in alloted:
            if each.hotelId not in booked_hotel:
                booked_hotel.append(each.hotelId)
    # print(booked_hotel)


    print(similarity_hotel[1][1])
    # print(similarity_hotel.shape)
    new_recommendation = []
    for each in booked_hotel:
        hotelNo = ''.join(filter(lambda i: i.isdigit(),each))
        # print(hotelNo)
        hotelNo = int(hotelNo)

        for i in range(similarity_hotel.shape[1]): # finding the hotels similar to the ones booked by user using hotel similarity matrix
            x = similarity_hotel[hotelNo][i]
            if x >= 0.94 :
                new_recommendation.append(i)
    # print(new_recommendation)
    return new_recommendation 
 

project/templates/adminLogin.html
{% extends "base.html" %}

{% block content %}
    <h1>Admin Login</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.userId.label }}<br>
            {{ form.userId(size=32) }}<br>
            {% for error in form.userId.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>

        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

project/templates/book.html
<!--

=========================================================
* Now UI Kit - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-kit
* Copyright 2019 Creative Tim (http://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/now-ui-kit/blob/master/LICENSE.md)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Hotel Registration
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/now-ui-kit.css')}}"/>
</head>

<body class="landing-page sidebar-collapse">
  <!-- Navbar -->
  <!-- <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-header">Dropdown header</a>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">One more separated link</a>
        </div>
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" href="https://demos.creative-tim.com/now-ui-kit/index.html" rel="tooltip" title="Designed by Invision. Coded by Creative Tim" data-placement="bottom" target="_blank">
          Now Ui Kit
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="../index.html">Back to Kit</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/creativetimofficial/now-ui-kit/issues">Have an issue?</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom" href="https://twitter.com/CreativeTim" target="_blank">
              <i class="fab fa-twitter"></i>
              <p class="d-lg-none d-xl-none">Twitter</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="https://www.facebook.com/CreativeTim" target="_blank">
              <i class="fab fa-facebook-square"></i>
              <p class="d-lg-none d-xl-none">Facebook</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom" href="https://www.instagram.com/CreativeTimOfficial" target="_blank">
              <i class="fab fa-instagram"></i>
              <p class="d-lg-none d-xl-none">Instagram</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav> -->
  <!-- End Navbar -->

  <nav class="navbar navbar-expand-lg bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link" href="{{url_for('admin.index')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('admin.Book')}}">Booking</a>
            </li>
            {% if current_user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.signup')}}">Signup</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.UserLogin')}}">Login</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('admin.adminLogin')}}">Admin</a>
              </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.userDashboard')}}">Dashboard</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.recommended')}}">Recommended</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.logout')}}">Logout</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    {% for x in range(0,22) %}
        <div class="card" style="width: 25rem;height:20rem ;"> 
            <div class="card-body">
                <h4 class="card-title">{{hotel_names[x]}}</h4>     
              <h6 class="card-subtitle mb-2 text-muted">{{hotel_address[x]}}</h6>
              {% if recommendation is defined%}

              {% else%}
                {% if x in recommendations %}
                &nbsp;&nbsp;
                <h6>Recommended for You </h6>
                {% endif %}
             {% endif %}
              <p> 
                  {% if facilities_list[x]['gym'] == true %}
                      Gym &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['FoodBeverages'] == true %}
                      Food & Beverages &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['Parking'] == true %}
                      Parking Facility &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['Tv'] == true %}
                      TV &nbsp;&nbsp;
                  {% endif %}
                  {% if facilities_list[x]['wifi'] == true %}
                      Free Wi-fi &nbsp;&nbsp;
                  {% endif %}
             </p> 
              <p class="card-text"></p>
              <a href="{{url_for('admin.book_info', hotelId = 'H' + (x)|string )}}" class="card-link">View Rooms</a>
            </div>
        </div>
        <br>
    {% endfor %}
    </div>




    <!-- hotel ends -->
    <footer class="footer footer-default">
      <div class=" container ">
        <nav>
          <ul>
            <li>
              <a href="">
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright" id="copyright">
          &copy;
          <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
          </script>, Made with &hearts; by Syntax Error!
        </div>
      </div>
    </footer>
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='js/core/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/popper.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/bootstrap.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-switch.js')}}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{url_for('static', filename='js/plugins/nouislider.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-datepicker.js')}}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='js/now-ui-kit.js')}}" type="text/javascript"></script>
</body>

</html>

project/templates/book_info.html
<!--

=========================================================
* Now UI Kit - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-kit
* Copyright 2019 Creative Tim (http://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/now-ui-kit/blob/master/LICENSE.md)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
      Hotel Registration
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}"/>  
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/now-ui-kit.css')}}"/>
</head>

<body class="landing-page sidebar-collapse" style="background: rgb(0, 7, 68);">
  

  <nav class="navbar navbar-expand-lg" style="background: rgb(0, 0, 71);">
    <div class="container">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item ">
            <a class="nav-link" href="{{url_for('admin.index')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admin.Book')}}">Booking</a>
          </li>
          {% if current_user.is_anonymous %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.signup')}}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.UserLogin')}}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('admin.adminLogin')}}">Admin</a>
            </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.userDashboard')}}">Dashboard</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admin.recommended')}}">Recommended</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('admin.logout')}}">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

    <!-- hotels -->

    <div class="container">
        <br>
        <br>
            <div class="card">              
                <div class="card-body">
                <h4 class="card-title"></h4>
                <div class="table-responsive">
                        <table class="table">
                                <thead class=" text-primary">
                                        <tr>
                                            <th>Room NO.</th>
                                            <th>Capacity</th>
                                            <th>Price</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                
                                <tbody>
                                {% for each in list %}
                                    <tr>
                                        <td>{{each['roomNo']}}</td>
                                        <td>{{each['capacity']}}</td>
                                        <td>{{each['price']}}</td>
                                        {% if each['status'] == false %}
                                            <td>Already booked</td>
                                        {% elif each['roomNo'] in draftList %}
                                        <td>
                                          <p>Draft Saved</p>
                                          <a href="{{url_for('admin.viewDraft')}}">View draft</a>
                                          </td>
                                        {% elif each['status'] == true %}
                                            <td>
                                            <p>Available</p>
                                            <a href="{{url_for('admin.book_room', hotelId = each['hotelId'] , roomNo = each['roomNo'])}}">Book Room</a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                </tbody>
                                </table>    
                </div>
                </div>
            </div> 
    </div>




    <!-- hotel ends -->
    <footer class="footer footer-default" style="background: rgba(0, 0, 0, 0.308);">
      <div class=" container ">
        <nav>
          <ul>
            <li>
              <a href="https://mayankdhiman.github.io/blog/">
                Blog
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright" id="copyright">
          &copy;
          <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
          </script>, Made with &hearts; by Syntax Error!
        </div>
      </div>
    </footer>
  </div>
  <!--   Core JS Files   -->
  <script src="{{url_for('static', filename='js/core/jquery.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/popper.min.js')}}" type="text/javascript"></script>
  <script src="{{url_for('static', filename='js/core/bootstrap.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-switch.js')}}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{{url_for('static', filename='js/plugins/nouislider.min.js')}}" type="text/javascript"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="{{url_for('static', filename='js/plugins/bootstrap-datepicker.js')}}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
  <script src="{{url_for('static', filename='js/now-ui-kit.js')}}" type="text/javascript"></script>
</body>

</html>

project/templates/book_room.html
{% extends "base.html" %}

{% block content %}

<div class="row pt-5 pb-3" style="padding-top:4cm; padding-left: 1cm; ">
    <div class = "col-md-6 mx-auto">
        <div class="card" style="padding:30pt,30pt,30pt,5pt; background-color: rgba(255, 255, 255, 0.726);">
            <div class="container" style="padding: 30pt,30pt,30pt,5pt;">
                            <h1 align="center"  style="color: #090341; padding-top: 5mm;" ;>Fill the Credentials</h1>
                            <hr>
                            <form action="" method="post">
                                {{ form.hidden_tag() }}
                                <p>
                                    {{ form.checkIn.label }}<br>
                                    {{ form.checkIn(size=32) }}<br>
                                    {% for error in form.checkIn.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                    {% endfor %}
                                </p>
                                <p>
                                    {{ form.checkOut.label }}<br>
                                    {{ form.checkOut(size=32) }}<br>
                                    {% for error in form.checkOut.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                    {% endfor %}
                                </p>
                                <p>
                                    {{ form.totalMembers.label }}<br>
                                    {{ form.totalMembers(size=32) }}<br>
                                    {% for error in form.totalMembers.errors %}
                                    <span style="color: red;">[{{ error }}]</span>
                                    {% endfor %}
                                </p>
                                <p align="center">{{ form.submit() }}</p>
                            </form>
                            </div>
        </div>
    </div>
    
{% endblock %} -->